service: aws
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: handler.qwikApp
    events:
      - httpApi: '*'

package:
  excludeDevDependencies: false

plugins:
  - serverless-offline
  - serverless-plugin-qwik
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
