service: aws
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: server/entry-aws-lambda.qwikApp
    events:
      - httpApi: '*'

custom:
  serverless-offline:
    httpPort: 4000
plugins:
  - serverless-offline