[workspace]

members = [
    "napi",
    "optimizer/cli",
    "optimizer/core",
    "wasm",
]

[profile.release]
lto="y"
codegen-units=1
opt-level="z"
# Not working at the moment because `swc_common`'s forced `crate-type` Cargo setting
# panic="abort"
