service: aws
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: '*'

custom:
  serverless-offline:
    httpPort: 4000

package:
  excludeDevDependencies: false

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
