[package]
authors = ["Manu <manu@builder.io>"]
name = "qwik-core"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/BuilderIO/qwik"
license = "MIT"
description = "Qwik optimizer compiler"
keywords = ["qwik", "swc", "javascript", "optimizer", "compiler"]
categories = ["development-tools", "development-tools::cargo-plugins"]

[lib]
crate-type = ["rlib"]

[dependencies]
swc_ecmascript = { version = "0.231", features = [
    "codegen",
    "utils",
    "visit",
    "parser",
    "transforms",
    "typescript",
    "react",
    "optimization",
] }
swc_common = { version = "0.31", features = ["sourcemap"] }
swc_atoms = "0.5"
serde = "1"
serde_bytes = "0.11"
serde_json = "1"
simple-error = "0.3"
base64 = "0.21"
pathdiff = "0.2"
relative-path = "1"
lazy_static = "1"
anyhow = "1"
derivative = "2"
rayon = "1"
path-slash = "0.2"

[dev-dependencies]
insta = "1"

[features]
fs = []
parallel = []
