name: Qwik CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node: [12.x]
        os: ['ubuntu-latest']

    name: Build (Node ${{ matrix.node }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Install Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Validate Build
        run: yarn validate.build

  lint:
    strategy:
      matrix:
        node: [12.x]
        os: ['ubuntu-latest']

    name: Lint (Node ${{ matrix.node }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Install Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Prettier Check
        run: yarn prettier-check

      - name: Lint Check
        run: yarn lint

  unit-tests:
    strategy:
      matrix:
        node: [12.x]
        os: ['ubuntu-latest']

    name: Unit Tests (Node ${{ matrix.node }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Node.js ${{ matrix.node }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Install Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Unit Tests
        run: |
          yarn build
          yarn test.unit

  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        node: [12.x]
        os: ['ubuntu-latest']
        containers: [1, 2, 3, 4]

    name: E2E Tests (Node ${{ matrix.node }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    steps:
      - name: Setup Node.js ${{ matrix.node }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: 'E2E Tests'
        uses: cypress-io/github-action@v2
        with:
          start: yarn integration.server.prod
          wait-on: 'http://localhost:8081'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'Qwik E2E Test Group'
          spec: cypress/integration/*
          config-file: cypress/cypress.json
          config: defaultCommandTimeout=5000
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
