name: Qwik CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ############ BUILD ############
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Prettier Check
        if: ${{ always() }}
        run: yarn lint.prettier

      - name: ESLint Check
        if: ${{ always() }}
        run: yarn lint.eslint

      - name: Build Package
        run: node scripts --tsc --build --api"

      - name: Build Create Qwik CLI
        run: node scripts --cli

      - name: Jest Unit Tests
        run: yarn test.unit
