name: default-ci-jobs
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - run: yarn lint
      - run: yarn build

      - name: Save build directories
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: |
            dist-dev
            integration/devserver.js

  unit-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: |
            dist-dev
            integration/devserver.js

      - run: yarn test.unit

  e2e-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: |
            dist-dev
            integration/devserver.js

      - name: 'E2E Tests'
        uses: cypress-io/github-action@v2
        with:
          start: yarn integration.server.prod
          wait-on: 'http://localhost:8081'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'E2E Test Group'
          spec: cypress/integration/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
