name: Qwik Packages Test Release

on:
  pull_request:
  push:
    branches:
      - main
      - next
      - qwik-labs
      - vercelserverless
      - 'build/**'

env:
  # Disable incremental build, speeds up CI
  CARGO_INCREMENTAL: 0

jobs:
  build-package:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        if: github.event_name == 'pull_request'
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install NPM Dependencies
        run: |
          # Ensure that the qwik binary gets made
          mkdir -p packages/qwik/dist/bindings/
          pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm tsm scripts/index.ts --tsc --build --cli --api --qwiklabs --qwikcity --eslint --platform-binding-wasm-copy --set-dist-tag="${{ github.event.inputs.disttag }}"

      - name: Build Eslint rules
        run: pnpm tsm scripts/index.ts --eslint

      - run: pnpm dlx pkg-pr-new@0.0.7 publish --compact --pnpm ./packages/qwik/dist ./packages/qwik-city/lib ./packages/eslint-plugin-qwik/dist ./packages/create-qwik/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
